import { CategoryType, ExpenseCategoriesType } from "@/types";
import { colors } from "./theme";

import * as Icons from "phosphor-react-native"; // Import all icons dynamically

export const expenseCategories: ExpenseCategoriesType = {
  groceries: {
    label: "Groceries",
    value: "groceries",
    icon: Icons.ShoppingCart,
    bgColor: "#4B5563", // Deep Teal Green
  },
  rent: {
    label: "Rent",
    value: "rent",
    icon: Icons.House,
    bgColor: "#075985", // Dark Blue
  },
  utilities: {
    label: "Utilities",
    value: "utilities",
    icon: Icons.Lightbulb,
    bgColor: "#ca8a04", // Dark Golden Brown
  },
  transportation: {
    label: "Transportation",
    value: "transportation",
    icon: Icons.Car,
    bgColor: "#b45309", // Dark Orange-Red
  },
  entertainment: {
    label: "Entertainment",
    value: "entertainment",
    icon: Icons.FilmStrip,
    bgColor: "#0f766e", // Darker Red-Brown
  },
  dining: {
    label: "Dining",
    value: "dining",
    icon: Icons.ForkKnife,
    bgColor: "#be185d", // Dark Red
  },
  health: {
    label: "Health",
    value: "health",
    icon: Icons.Heart,
    bgColor: "#e11d48", // Dark Purple
  },
  insurance: {
    label: "Insurance",
    value: "insurance",
    icon: Icons.ShieldCheck,
    bgColor: "#404040", // Dark Gray
  },
  savings: {
    label: "Savings",
    value: "savings",
    icon: Icons.PiggyBank,
    bgColor: "#065F46", // Deep Teal Green
  },
  clothing: {
    label: "Clothing",
    value: "clothing",
    icon: Icons.TShirt,
    bgColor: "#7c3aed", // Dark Indigo
  },
  personal: {
    label: "Personal",
    value: "personal",
    icon: Icons.User,
    bgColor: "#a21caf", // Deep Pink
  },
  others: {
    label: "Others",
    value: "others",
    icon: Icons.DotsThreeOutline,
    bgColor: "#525252", // Neutral Dark Gray
  },
};

export const incomeCategory: CategoryType = {
  label: "Income",
  value: "income",
  icon: Icons.CurrencyDollarSimple,
  bgColor: "#16a34a", // Dark
};

export const transactionTypes = [
  { label: "Expense", value: "expense" },
  { label: "Income", value: "income" },
];


export const  currencyList = [
  { code: "AED", symbol: "د.إ" },
  { code: "AFN", symbol: "؋" },
  { code: "ALL", symbol: "L" },
  { code: "AMD", symbol: "֏" },
  { code: "ANG", symbol: "ƒ" },
  { code: "AOA", symbol: "Kz" },
  { code: "ARS", symbol: "$" },
  { code: "AUD", symbol: "$" },
  { code: "AWG", symbol: "ƒ" },
  { code: "AZN", symbol: "₼" },
  { code: "BAM", symbol: "KM" },
  { code: "BBD", symbol: "$" },
  { code: "BDT", symbol: "৳" },
  { code: "BGN", symbol: "лв" },
  { code: "BHD", symbol: ".د.ب" },
  { code: "BIF", symbol: "FBu" },
  { code: "BMD", symbol: "$" },
  { code: "BND", symbol: "$" },
  { code: "BOB", symbol: "Bs." },
  { code: "BRL", symbol: "R$" },
  { code: "BSD", symbol: "$" },
  { code: "BTN", symbol: "Nu." },
  { code: "BWP", symbol: "P" },
  { code: "BYN", symbol: "Br" },
  { code: "BZD", symbol: "$" },
  { code: "CAD", symbol: "$" },
  { code: "CDF", symbol: "FC" },
  { code: "CHF", symbol: "CHF" },
  { code: "CLP", symbol: "$" },
  { code: "CNY", symbol: "¥" },
  { code: "COP", symbol: "$" },
  { code: "CRC", symbol: "₡" },
  { code: "CUC", symbol: "$" },
  { code: "CUP", symbol: "$" },
  { code: "CVE", symbol: "$" },
  { code: "CZK", symbol: "Kč" },
  { code: "DJF", symbol: "Fdj" },
  { code: "DKK", symbol: "kr" },
  { code: "DOP", symbol: "RD$" },
  { code: "DZD", symbol: "دج" },
  { code: "EGP", symbol: "£" },
  { code: "ERN", symbol: "Nfk" },
  { code: "ETB", symbol: "Br" },
  { code: "EUR", symbol: "€" },
  { code: "FJD", symbol: "$" },
  { code: "FKP", symbol: "£" },
  { code: "FOK", symbol: "kr" },
  { code: "GBP", symbol: "£" },
  { code: "GEL", symbol: "₾" },
  { code: "GGP", symbol: "£" },
  { code: "GHS", symbol: "GH₵" },
  { code: "GIP", symbol: "£" },
  { code: "GMD", symbol: "D" },
  { code: "GNF", symbol: "FG" },
  { code: "GTQ", symbol: "Q" },
  { code: "GYD", symbol: "$" },
  { code: "HKD", symbol: "$" },
  { code: "HNL", symbol: "L" },
  { code: "HRK", symbol: "kn" },
  { code: "HTG", symbol: "G" },
  { code: "HUF", symbol: "Ft" },
  { code: "IDR", symbol: "Rp" },
  { code: "ILS", symbol: "₪" },
  { code: "IMP", symbol: "£" },
  { code: "INR", symbol: "₹" },
  { code: "IQD", symbol: "ع.د" },
  { code: "IRR", symbol: "﷼" },
  { code: "ISK", symbol: "kr" },
  { code: "JMD", symbol: "$" },
  { code: "JOD", symbol: "د.ا" },
  { code: "JPY", symbol: "¥" },
  { code: "KES", symbol: "KSh" },
  { code: "KGS", symbol: "лв" },
  { code: "KHR", symbol: "៛" },
  { code: "KID", symbol: "$" },
  { code: "KMF", symbol: "CF" },
  { code: "KRW", symbol: "₩" },
  { code: "KWD", symbol: "د.ك" },
  { code: "KYD", symbol: "$" },
  { code: "KZT", symbol: "₸" },
  { code: "LAK", symbol: "₭" },
  { code: "LBP", symbol: "ل.ل" },
  { code: "LKR", symbol: "Rs" },
  { code: "LRD", symbol: "$" },
  { code: "LSL", symbol: "L" },
  { code: "LYD", symbol: "ل.د" },
  { code: "MAD", symbol: "د.م." },
  { code: "MDL", symbol: "L" },
  { code: "MGA", symbol: "Ar" },
  { code: "MKD", symbol: "ден" },
  { code: "MMK", symbol: "K" },
  { code: "MNT", symbol: "₮" },
  { code: "MOP", symbol: "MOP$" },
  { code: "MRU", symbol: "UM" },
  { code: "MUR", symbol: "Rs" },
  { code: "MVR", symbol: "Rf" },
  { code: "MWK", symbol: "MK" },
  { code: "MXN", symbol: "$" },
  { code: "MYR", symbol: "RM" },
  { code: "MZN", symbol: "MT" },
  { code: "NAD", symbol: "$" },
  { code: "NGN", symbol: "₦" },
  { code: "NIO", symbol: "C$" },
  { code: "NOK", symbol: "kr" },
  { code: "NPR", symbol: "Rs" },
  { code: "NZD", symbol: "$" },
  { code: "OMR", symbol: "﷼" },
  { code: "PAB", symbol: "B/." },
  { code: "PEN", symbol: "S/" },
  { code: "PGK", symbol: "K" },
  { code: "PHP", symbol: "₱" },
  { code: "PKR", symbol: "Rs" },
  { code: "PLN", symbol: "zł" },
  { code: "PYG", symbol: "₲" },
  { code: "QAR", symbol: "﷼" },
  { code: "RON", symbol: "lei" },
  { code: "RSD", symbol: "дин" },
  { code: "RUB", symbol: "₽" },
  { code: "RWF", symbol: "FRw" },
  { code: "SAR", symbol: "﷼" },
  { code: "SBD", symbol: "$" },
  { code: "SCR", symbol: "Rs" },
  { code: "SDG", symbol: "ج.س." },
  { code: "SEK", symbol: "kr" },
  { code: "SGD", symbol: "$" },
  { code: "SHP", symbol: "£" },
  { code: "SLL", symbol: "Le" },
  { code: "SOS", symbol: "Sh" },
  { code: "SRD", symbol: "$" },
  { code: "SSP", symbol: "£" },
  { code: "STN", symbol: "Db" },
  { code: "SYP", symbol: "£" },
  { code: "SZL", symbol: "L" },
  { code: "THB", symbol: "฿" },
  { code: "TJS", symbol: "SM" },
  { code: "TMT", symbol: "T" },
  { code: "TND", symbol: "د.ت" },
  { code: "TOP", symbol: "T$" },
  { code: "TRY", symbol: "₺" },
  { code: "TTD", symbol: "TT$" },
  { code: "TVD", symbol: "$" },
  { code: "TWD", symbol: "NT$" },
  { code: "TZS", symbol: "Sh" },
  { code: "UAH", symbol: "₴" },
  { code: "UGX", symbol: "USh" },
  { code: "USD", symbol: "$" },
  { code: "UYU", symbol: "$U" },
  { code: "UZS", symbol: "лв" },
  { code: "VES", symbol: "Bs.S" },
  { code: "VND", symbol: "₫" },
  { code: "VUV", symbol: "VT" },
  { code: "WST", symbol: "WS$" },
  { code: "XAF", symbol: "FCFA" },
  { code: "XCD", symbol: "$" },
  { code: "XOF", symbol: "CFA" },
  { code: "XPF", symbol: "₣" },
  { code: "YER", symbol: "﷼" },
  { code: "ZAR", symbol: "R" },
  { code: "ZMW", symbol: "ZK" },
  { code: "ZWL", symbol: "$" },
];